name: main 
on: [push]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    container: tg9541/docker-sdcc:V3.9.0
    steps:
      - run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch name:  ${{ github.ref }}"
          echo "repository:   ${{ github.repository }}"
          echo "workspace:    ${{ github.workspace }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          pwd
          make BOARD=test forth
          make clean
          make all
      - run: echo "This job's status is ${{ job.status }}."
